Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ecomm_app.views import index, contact

urlpatterns = [
    path('', index, name='index'),
    path('items/', include('items.urls')),
    path('contact/', contact, name='contact'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomm_app/urls.py
from django.urls import path
from . import views

app_name = 'ecomm_app'
urlpatterns = [
    path('', views.index, name='index'),
]

items/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

ecomm_app/models.py
from django.db import models

# Create your models here.

items/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name= models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='item', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank = True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

ecomm_app/views.py
from django.shortcuts import render
from items.models import Category, Item

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold = False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html',{
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

items/views.py
from django.shortcuts import render, get_object_or_404
from items.models import Item

# Create your views here.
# def items(request):
#     return render(request, 'core/items.html')

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

items/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %} {{ item.name }} {% endblock %}

{% block content %} 
    <div class="grid grid-cols-5 gap-6">
        <div class"col-span-3">
            <img src="{{ item.image.url }}" class="rounded-xl">
        </div>

        <div class="col-span-2 p-6 bg-gray-200 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-gray-500"><strong>Price: </strong>{{ item.price }} </p>
            <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }} </p>

            {% if item.description %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Description:</strong><br>
                    {{ item.description }}
                </p>
            {% endif %}

            <a href="#" class="inline-block mt-6 px-3 py-6 text-lg font-semibold bg-teal-600 text-white rounded-xl hover:bg-teal-700">Contact Seller</a>
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related Items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/core/base.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>
        {% block title %} {% endblock title %} | Ecommerce
    </title>
</head>

<body>
    <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Ecommerce</a>
        
        <div class="space-x-6">
            <a href="#" class="text-lg font-semibold hover:text-gray-600">New Item</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-600">Browse</a>

            <a href="#" class="px-6 py-6 text-lg font-semibold bg-teal-600 text-white rounded-xl hover:bg-teal-800">Sign Up</a>
            <a href="#" class="px-6 py-6 text-lg font-semibold bg-gray-600 text-white rounded-xl hover:bg-gray-800">Log In</a>
        </div>
    </nav>
    <div class="px-6 py-6">
        <h1>
            {% block content %} {% endblock content %}
        </h1>
    </div>

    <footer class="px-6 py-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>

            <p class="text-lg text-gray-500">Welcome to Ecommerce!
                <br>At Ecommerce, we're your go-to destination for all your shopping needs. With a wide range of products and a seamless shopping experience, we're here to make your online shopping journey enjoyable and convenient.
                
                Our Mission
                Our mission is to provide you with the best shopping experience possible. We're committed to offering high-quality products, exceptional customer service, and secure transactions every step of the way.
                
                Who We Are
                Behind Ecommerce is a dedicated team of e-commerce enthusiasts who are passionate about bringing you the latest trends and best deals. With years of experience in the industry, we're here to make sure you find exactly what you're looking for.
                
                What We Offer
                Explore our extensive collection of products, including clothing, accessories, electronics, home goods, and much more. With fast shipping and easy returns, shopping with us is hassle-free and enjoyable.
                
                Join Us on Our Shopping Journey
                Join us on our mission to redefine online shopping. Whether you're shopping for yourself or searching for the perfect gift, we're here to help you find exactly what you need. Thank you for choosing Ecommerce for all your shopping needs!</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms and Conditions</a></li>
            </ul>
        </div>
    </footer>
</body>

</html>

templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact
{% endblock title %}

{% block content %}
<h1>Welcome to the Contact Page!</h1>
{% endblock content %}

templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Home
{% endblock title %}

{% block content %}
{% comment %} Showing New Items {% endcomment %}
    <div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    {% comment %} Showing the Total number of Items in the Category of Products {% endcomment %}
    <div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.item.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}